language: go
go:
- 1.12
branches:
  only:
  - master
  - develop
services:
- docker
env:
  global:
  - GO111MODULE=on
  - secure: eEYvcMMMxsBM8EkjylxZVzfD70KoMiQ9uxnO1mWjIi3mYaLj9NZIWgxEAweg7uq4EQ+B+q5kYQP2HdgRZJSlYCoWOgPVbFS+jHBqRiquPN4NhO6QHICxfuvAylbSBhqkxtOAf4HFBA/a1vkuSp8RQ+rdIteXceMGJimyYwffKUN7UTsXnOwRRYrFfYW5Gr9X2vS1y1acRZGZymwsLzCcXNZIEgjzYmMRhqhv+vVR4+PHUDWOhyfXxoqncxqOjAl5hLwGYxCoeJFZ5GU1aZ7GlJl7s/jOno14uoqhiMXBG0znzIJV16EF8XGfxYoiGWeNIJCyHiDA1gRbVAiL7IeorRueQ+xsNofk/i0wmw46Uxvf4uxcZhRCixV50pVKIjRMSmJDTte+Ddx5d0/Ureq7W04d2U5K6c9EaLsTfxjgNua6YJU8luCdg4wanRMxcBrIjJN6tLaIMLKuQMYEZZ/HLWLm3dQ+0rItNiNxzYpEE1hcpYzLspVZUJV2PrsE1RHqRkBWNE3dpSHHbSLvB+3LFrlubLfaAZB1kkOVxc3YdNYLHB+BxmGohVN8kbfbchfFww9dsPzaCzgf4xI13Bto9rP9MbHygK+LOR+P+YtI/WRd6m66LcSdpq5mUb7FAS4LQKGzmM4mdvTWoM8iLiDvyp2g4m2Xsx6bfx8CebTwYFk=
  - secure: XRFHHasnaxqQ97/mX1gJl47FQfT6FC2rL2w8ovmLXd9OpgkAI0ZKr4IVggbuqnEOWfmR/JOigvSFZIwH1llqQkT/a48BR+lhDNI4lbwzBpk0EIxzGmw7kutqlUT8zX91kkUSokWj2Z1Xe7tnmHDoTMZ5eig6SbgZx4WF0hrxl/6ZjoZeFWxJTZiD2Px2myrwSF8xFHPQC6dyp3wuRhWDaAPvj0M6Djq257eKmobIw22JIrMUX8dTLuVq2HwMUPteUB55iFQ2pbPuQYE3v6sV9XglgNnoSwIW1ZAWf28HasUy/HddI/EWzNmthHIdHp+xi/QI/UVyklUckbUYPFy0QmJiRBT1KXKs9em0YAgpEifXNVvOjfNspD3+kkZa/0q26nWUU6VD/RIugf9faPgwSxvgjILetX2oS+Vn08lt97I3EUtGmf+cXtYqfjv6pBvDVLmQ6Mv/P/Y/f4TkiRA4/eTjB7zj0AIRZf8pvm5OVv+4Vr+3f1otfP7OWEm3ogNnnE6ZAY05iu9v8fzYQfA2v73jgsU5mnxqXbKfOrwqmXU1OgoCPGErg46akNWpHvN0uD58p3RDNyqHV4lXBng455qkB/dUo5/bRJbKejrxRg3Br2eH6imMDwuVJjO7AWKwt9YL/HkprR9AkFsfDekWfSZKmD6iHxDMsWcwV3HxQFA=
before_script:
- export BUILD_DATE=`date +%FT%T%z`
- export VERSION=${TRAVIS_TAG:-0.0.0}
- export LDFLAG_LOCATION=main
- export LDFLAGS="-X ${LDFLAG_LOCATION}.version=${VERSION} -X ${LDFLAG_LOCATION}.buildDate=${BUILD_DATE}
  -X ${LDFLAG_LOCATION}.buildNumber=${TRAVIS_BUILD_NUMBER} -X ${LDFLAG_LOCATION}.gitCommit=${TRAVIS_COMMIT}"
- export PATH=$PATH:$PWD
- echo ${DOCKER_PASSWORD} | docker login -u="${DOCKER_USERNAME}" --password-stdin
  quay.io
script:
- go test .
- go build -ldflags "${LDFLAGS}" -o build/kube-pod-rescheduler
- chmod +x build/kube-pod-rescheduler
- build/kube-pod-rescheduler
- docker build -t quay.io/maxvasylets/kube-pod-rescheduler:${VERSION}-${TRAVIS_BUILD_NUMBER} .
- docker tag quay.io/maxvasylets/kube-pod-rescheduler:${VERSION}-${TRAVIS_BUILD_NUMBER}
  quay.io/maxvasylets/kube-pod-rescheduler:latest
- docker push quay.io/maxvasylets/kube-pod-rescheduler:${VERSION}-${TRAVIS_BUILD_NUMBER}
- docker push quay.io/maxvasylets/kube-pod-rescheduler:latest
